name: Pull Request
description: Pull Request 템플릿
title: ""
labels: []
assignees: []
body:
  - type: checkboxes
    id: pr-type
    attributes:
      label: "✅ PR 유형"
      description: "어떤 변경 사항이 있었나요?"
      options:
        - label: "새로운 기능 추가"
        - label: "버그 수정"
        - label: "리팩토링"
        - label: "코드에 영향을 주지 않는 변경사항(주석, 개행 등등..)"
        - label: "문서 수정"
        - label: "빌드 부분 혹은 패키지 매니저 수정"
        - label: "테스트 코드 추가"
    validations:
      required: true

  - type: textarea
    id: work-content
    attributes:
      label: "✏️ 작업 내용"
      description: "스크린샷 첨부는 **필수**입니다!"
      placeholder: "변경 내용을 자세히 설명해주세요. 스크린샷을 첨부해주세요."
    validations:
      required: true

  - type: input
    id: related-issue
    attributes:
      label: "🔗 관련 이슈"
      placeholder: "closes #1"
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: "💡 추가 사항"
      placeholder: "추가로 전달하고 싶은 내용이 있다면 작성해주세요."
    validations:
      required: false
