name: "⚡️ performance"
description: 성능 개선 이슈 템플릿
title: "[Performance] "
labels: ["⚡️ performance"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 이슈 내용 설명
  - type: textarea
    id: description
    attributes:
      label: 설명
      description: 성능 개선이 필요한 내용을 설명해주세요.
      placeholder: 성능 개선할 내용을 자세히 설명해주세요.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ✅ TODO
  - type: textarea
    id: todo
    attributes:
      label: 할 일 목록
      description: 성능 개선을 위한 작업 목록을 작성해주세요.
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
    validations:
      required: true

